# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 04:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdate', models.DateField()),
                ('hours', models.PositiveSmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workcode', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='timesheetdetail',
            name='workcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Workcode'),
        ),
    ]
